apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: test-no-sbom-sept12-gitops-on-pull-request
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/pipeline: "https://raw.githubusercontent.com/Jdubrick/ai-rhdh-tekton-pipelines/pipeline-definition-overhaul/pac/pipelines/gitops-pull-request-ai-rhdh.yaml"
    pipelinesascode.tekton.dev/task-0: "https://raw.githubusercontent.com/Jdubrick/ai-rhdh-tekton-pipelines/pipeline-definition-overhaul/pac/tasks/git-clone.yaml"
  labels:
    argocd/app-name: test-no-sbom-sept12
    janus-idp.io/tekton: test-no-sbom-sept12
    backstage.io/kubernetes-id: test-no-sbom-sept12
    backstage.io/kubernetes-namespace: rhtap-app
    app.kubernetes.io/part-of: test-no-sbom-sept12
spec:
  params:
    - name: git-url
      value: '{{repo_url}}'
    - name: revision
      value: '{{revision}}'
    - name: target-branch
      value: '{{target_branch}}'
  pipelineRef:
    name: gitops-pull-request
  workspaces:
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
